# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ # désactive la sécurité pour ces chemins
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # Optionnellement, spécifiez où rediriger après la déconnexion
                # target: app_home_index

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /login
                always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/products, roles: ROLE_USER }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/cart, roles: ROLE_USER }
        
        
